[toolchain]
channel = "nightly-2024-03-17"
components = ["rustc", "cargo", "rust-std", "rustfmt", "clippy"]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc",
    "x86_64-apple-darwin",
    "aarch64-unknown-linux-gnu",
    "aarch64-pc-windows-msvc",
    "aarch64-apple-darwin",
    "wasm32-wasi",
    "wasm32-unknown-unknown"
]